version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  # IMPORTANT: This tells RTD to look inside your new 'website' folder!
  # If your conf.py is inside website/source/conf.py, change this line to match.
  configuration: website/source/conf.py